### ISSUE TITLE
[Lettuce] List user threads

### ISSUE THREAD

**Issue by sloik** [sloik/seller#17]
Create request object and DTO for: https://developer.allegro.pl/documentation#operation/listThreadsGET

**Comment by dtawrel** [comment]
https://www.figma.com/file/Td1uDjw7Ma6wfyGAcHFiMT/SallerApp-2.0?type=design&node-id=0-1&mode=design&t=s0YSogeTvP2q5i7s-0 Podrzucam moki. Potrzebuję Waszych adresów, żeby udostępnić figmę. Work in progress bardzo 😄
