### ISSUE TITLE
Podział aplikacji na sekcje.

### ISSUE THREAD

**Issue by dtawrel** [sloik/seller#7]
Aplikacja powinna mieć dwie sekcje nawigacyjne ([tab bar](https://developer.apple.com/design/human-interface-guidelines/tab-bars)):

Wiadomości | Ustawienia

Logowanie powinno zostać przenisiesione do ustawień

**Comment by sloik** [comment]
Co z listingami, szczegółami oferty takie MVP? :)

**Comment by dominika-kokowicz** [comment]
@dtawrel Podbijam :)

**Comment by dtawrel** [comment]
Imo wydać można wersję obsługującą same wiadomości i podstawowe ustawienia. ;)
